### ISSUE TITLE
Dịch tù

### ISSUE THREAD

**Issue by dominhhai** [dominhhai/nodeschool.github.io#1]
@minatu2d Có chỗ nào lởm anh comment vào đây cũng OK nhé.

Cách chạy phía local:
## Cài đặt cho lần đầu
1. Clone project: `git clone https://github.com/dominhhai/nodeschool.github.io.git nodeschool-web`
2. Vào thư mục project: `cd nodeschool-web`
3. Cài các gói phụ thuộc: `npm install`
## Cho các lần sau
1. Pull project: `git pull origin master`
## Chạy chương trình
1. Bật local-server: `npm start`
2. Truy cập: `http://localhost:8080/`
3. Tắt server: tổ hợp phím `CTRL + C`

**Comment by minatu2d** [comment]
ok chú.

**Comment by minatu2d** [comment]
Browserify Adventure
Sử dụng các mô-đun npm và require() như lập trình với node trên trình duyệt với browserify.
=>
Có phải của chỗ này là

Sử dụng các module của Nodejs trên trình duyệt Web phía Client với browserify

**Comment by dominhhai** [comment]
:+1:

**Comment by dominhhai** [comment]
Others?

**Comment by minatu2d** [comment]
Xây dựng bài giảng

=> Xây dựng một workshopper.

Phía trên đã định nghĩa từ workshopper rồi mà.

**Comment by dominhhai** [comment]
À, em nghĩ hai từ này dùng đều được anh ạ. đổi đổi 1 tý cho vui ý mà :dancers:

**Comment by minatu2d** [comment]
Hết trang index rồi đấy.

**Comment by dominhhai** [comment]
:+1:
